### ISSUE TITLE
Meeste datatypes komen niet door in TBL extract fresnel naar wiki.

### ISSUE THREAD

**Issue by jheijning** [ABI-Team-30/Fresnel-Forms#57]
Op onze SVN in Environment & Misc\Ontologies\DBPedia_TBL_Extract staat nu ook een fresnel output van Fresnel Forms. Zoals je kunt zien hebben de properties met het probleem geen format en dus ook geen datatype. Omdat ik in een latere fresnel2wiki upload de property paginas van Alex' file heb overgeschreven laat de Tim_Berners_Lee de caption value bijvoorbeeld als pagina zien en niet als String.

@TeunTheunissen enig idee hoe dit komt? Of anders @AlexMekkering 

ps. het uploaden van de fresnel file van Alex gaf een error in Protégé.

**Comment by TeunTheunissen** [comment]
Ik ga ernaar kijken.

**Comment by jheijning** [comment]
Ik heb net een interessante test gedaan: Als je de ThingLens *niet* hide, dan komen de data properties weer wel tevoorschijn!

Het mysterie is opgelost :-) Als je de Thing lens *niet* hide, dan komen de datatypes wél goed door in Wiki. Dus wat dat betreft is het opgelost. Alleen is het dus niet mogelijk om de lens waarvan een sublens de properties inherit, te hiden.

**Comment by TeunTheunissen** [comment]
Dat is interesseant, zelf zag ik dat de title en birthName properties geen range definitie hadden en dus geen type definitie. Het lijkt er ook op dat een domain propery verplicht is anders wordt een range property genegeerd.

**Comment by TeunTheunissen** [comment]
Nu snap ik het beter, veel properties hebben als domein owl:Thing staan. Dus blijkbaar wordt een hiden owl:Thing als een niet bestaand domein beschouwd.

**Comment by TeunTheunissen** [comment]
DBpedia extract aangepast met de awards. de wikipagina gegenereerd met deze versie staat op:
http://abiteam30.lukylx.org:3080/mediawiki/index.php/Tim_Berners_Lee_%28test_v2_24022015%29%29

De aangepast fresnel staat in: 
Environment & Misc\Ontologies\DBPedia_TBL_Extract\TBL_extract_person.n3

Ik heb een paar bugs ontdekt:
1) De css van een label wordt overriden door de css style van de hyperlink. klopt want het is een hyperlink. Maar hierdoor kan bv de font color niet op zwart gezet worden.

2) Bij parent wordt de \n niet omgezet in een <p> zoals wel bij awards en employer gebeurd.

3) De website is geen external URL, terwijl dat wel in de fresnel gedefinieerd is.

@jheijning punt 1 is dat by design? Het is namelijk de link naar de property definitie pagina. Punt 2 heb je al eens genoemd, ben je er al verder mee gekomen, waar kan ik het oppikken?
punt 3, in de wiki xml export file ziet een external URL eruit als een gewoon veld. klopt dat? kan ik ermee aan de slag?
vr.gr. Teun

**Comment by jheijning** [comment]
ad 1) Niet bij design, blijkbaar is er een "uber" functie van mediawiki die als allerlaatste nog css aan hyperlinks toevoegt, niets aan te doen lijkt me.
2) Niet meer naar gekeken, wel heel vreemd :-) 
3) Je bedoelt Has type = "Page"?  hebben external URL's niet automatisch owf:datatype URL? of komt het alleen in de fresnel:value fresnel:url te staan? INdien dat zo is is dat niet goed natuurlijk. Er was denk ik een reden dat ik hier niets mee gedaan heb, maar misschien zou er net als bij image in writebox gechecked worden op "isURL" en dan hasType= url gegeven worden?

**Comment by TeunTheunissen** [comment]
Prima, ik ga ermee aan de slag.
punten 1 en 3 zijn al opgelost nog even committen.

**Comment by jheijning** [comment]
OK, die punten 1 en 3 staan apart als issue, kan dit issue gesloten worden?

**Comment by AlexMekkering** [comment]
- punt 1 wordt afgedekt door #59.
 - punt 2 is opgelost met #63.
 - punt 3 wordt afgedekt met #60.

dus... dit issue kan gesloten worden.
